341 - Transferring funds to non-existing or pre-compiled addresses
LimeChain/besu pull request #2
Opened 2021-07-29 10:22 UTC by alshapi

Signed-off-by: alshapi <alexander.shapkarov@limechain.tech>

## PR description

## Fixed Issue(s)

## Changelog

- [ ] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

2021-07-30 06:22 UTC, failfmi commented on ethereum/core/src/main/java/org/hyperledger/besu/ethereum/worldstate/DefaultMutableWorldState.java
> +      }
```suggestion
        // Clear structures
        wrapped.updatedStorageTries.clear();
        // Commit account state changes
        wrapped.accountStateStore.commit();
```

2021-08-04 12:21 UTC, failfmi commented
Wouldn't be enough to only add `exceptionalHaltReason` in `TransactionProcessingResult`?

2021-08-04 13:08 UTC, alshapi commented
It would be enough, if we change the signature of the `failed()` method and pass the `exceptionalHaltReason ` as an argument there, but then we will have to adjust all usages of the method.

2021-08-05 10:39 UTC, failfmi commented on ethereum/core/src/main/java/org/hyperledger/besu/ethereum/processing/TransactionProcessingResult.java
> +    this.exceptionalHaltReason = exceptionalHaltReason;
I think this is unnecessary, you can just add to the other constructor `final Optional<ExceptionalHaltReason> exceptionalHaltReason` and depending on the call pass `Optional.empty()` or `exceptionalHaltReason`

2021-08-06 11:04 UTC, failfmi approved these changes

2021-08-09 06:05 UTC, Daniel-K-Ivanov requested changes

2021-08-09 06:05 UTC, Daniel-K-Ivanov commented on ethereum/core/src/main/java/org/hyperledger/besu/ethereum/vm/operations/CallOperation.java
> +    if (frame.getWorldState().get(address(frame)) == null) {
I think that it is better for us to check for `null` in the `abstract execute` for several reasons:

1.  if we put it in the `super.execute` we will cover all call-like operations, not only `Call`
2. Accessing `account` from state is expensive. We are accessing it in the `super.execute` and there we can check for `null`. That way we will remove 1 unnecessary loading from state

2021-08-09 06:05 UTC, Daniel-K-Ivanov commented on ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetMessageCallProcessor.java
> +    // TODO review getOrCreate ?
Question: What do you mean by review? Think about how you can test it. How you can test the code so that `frame.getRecipientAddress` is non-existing account? Can you get to this state

2021-08-18 06:45 UTC, failfmi approved these changes

2021-08-18 11:22 UTC, Daniel-K-Ivanov approved these changes

2021-08-18 11:22 UTC, merged